spring:
  liquibase:
    change-log: /db/changelog/db.changelog-master.yaml
server:
  port: 8083
  servlet:
    context-path: /api/v1
logging:
  level:
    "liquibase" : info
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:liquibasedemo
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
